### PR TITLE
329 profile birthday

### LINKED ISSUE #329: Profile birthday incorrect
## Acceptance Criteria

- [ ] It should display the users birthday if available.
- [ ] It should have an appropriate blank/unfilled state.

## Context

Currently the a users birthday is displayed as the current date in Profile>Personal Details

## UI Screenshot or Wireframe (optional)
simulator screen shot - iphone x - 2018-02-09 at 10 47 40

### PR DESCRIPTION
**Pull request by burkeshartsis**
Fixes #329 

## Creator

- [x] Build relevant tests if any apply
- [x] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by burkeshartsis** [comment]
@cdanwards happy to explain the changes in this PR if you want.

**Comment by burkeshartsis** [comment]
@conrad-vanl Moment is weird

> `moment.month()` [...] Accepts numbers from 0 to 11.

I removed what looked like some silly logic but was more necessary than I thought.

https://momentjs.com/docs/#/get-set/month/

**Comment by conrad-vanl** [comment]
image

**Comment by conrad-vanl** [comment]
image

**Comment by conrad-vanl** [comment]
image

**Pull request merged**
