### PR TITLE
104 give logic

### LINKED ISSUE #104: Build give ContributionForm and payment flow
## Acceptance Criteria

- [ ] It should create a mostly unstyled but functional payment form
- [ ] It should use related mutations

### PR DESCRIPTION
**Pull request by Lepozepo**
Fixes #104 

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by Lepozepo** [comment]
I'm almost certain this payment flow works (it follows the same flow as their current app but patches some issues). Obviously all the form elements are crap. I think there's a big opportunity in the way the functions are divided though. The business logic feels a bit spread to me and the way resolvers are split isn't very nice. What opportunities do you see @conrad-vanl ?

**Comment by Lepozepo** [comment]
@conrad-vanl yep! I'll have a look as soon as I get accounts moving

**Comment by conrad-vanl** [comment]
On web it looks like they create a second order like you said, and the order mutation that is done at the end uses a different token then the one that is used to validate the credit card.

I tried doing that....but then I started getting a "order not found" style error 🤷‍♂️

**Comment by conrad-vanl** [comment]
But...fwiw....this branch should be "shippable" from a UI perspective - loading states, client-side validation, basic error handling at the end.

Will need another design pass later on, and some work on the `Success` page once we can get a success page loading :)

Would love thoughts on file structure / the form components can probably be cleaned up a lot more.

**Comment by Lepozepo** [comment]
Awesome! I'll have a look as soon as I can ^_^

**Comment by conrad-vanl** [comment]
Cool! And, I have some debug info on my end for the errors at the end. I have a slight idea on whats going on, and I have a network trace from a successful transaction flow on the current app that I can show you. So when you want to sync up on this happy to 👍

**Comment by Lepozepo** [comment]
@conrad-vanl the logic is working now ^_^ the code can use a lot of house cleaning under `/withGive` but I can do that in the saved payments PR so we can get this one merged :D

**Comment by Lepozepo** [comment]
Here's a preview of it working with dummy data

newspring

**Pull request merged**
