### PR TITLE
[SYS-4562] Fix Fund Loading

### PR DESCRIPTION
**Pull request by richarddubay**
Creator
-------

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

Reviewer
--------

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by richarddubay** [comment]
Okay ... so maybe it's not _quite_ ready yet. I'm seeing (a) flashes of "Uh oh" before the fund section loads and on Android it still isn't loading correctly. I'll keep trying.

**Comment by richarddubay** [comment]
@cdanwards @redreceipt Okay, I think this is right now.

**Comment by richarddubay** [comment]
To test this:
Start up the app.
Make sure you're logged out.
Go to giving.
Put in an amount and click to sign in.
Sign in.
When it takes you back to giving, the screen should load normally.
Put in an amount to give and click review.
The fund should be loaded correctly.

**Comment by richarddubay** [comment]
@IsaacHardy I went ahead and added you here so that you can take a look and see if this meets the requirements so that we can move forward.

**Comment by IsaacHardy** [comment]
So this is @cdanwards fault? ;p

**Comment by redreceipt** [comment]
I got an error...

screen shot 2018-11-15 at 10 38 06 pm

**Comment by IsaacHardy** [comment]
@redreceipt What can I do to replicate your error?

**Comment by redreceipt** [comment]
> @redreceipt What can I do to replicate your error?

@IsaacHardy not sure. I just know I'm getting this error trying to give the normal way.

**Comment by cdanwards** [comment]
@IsaacHardy @richarddubay After testing it looks like this allows the infinite loading screen error to happen again. The complexity of all of the HOC's in this file makes it hard to determine where that `branch` should happen so that it has the context it needs without breaking the fund input.

**Comment by richarddubay** [comment]
@cdanwards Can you show me how you got it to do the spinning? I'm going to test again, but this was working on all three environments the other day. Thanks!

**Comment by redreceipt** [comment]
@IsaacHardy @cdanwards it showed the loading error for me and then I pulled in @richarddubay's changes from yesterday and it worked. Pull in lastest and test again and let's merge this puppy!

**Pull request merged**
