### PR TITLE
409 Second address field validation fix

### LINKED ISSUE #409: Next button disabled on the address page of adding a new payment account
## Acceptance Criteria

- [ ] It should allow a person to click the "Next" button when all necessary items have been added for the address when adding a new payment account.

## Context

Given that a user has entered all of the correct information for the address when attempting to add a new payment account then they should be allowed to click or tap the "Next" button. Right now it is disabled.

## UI Screenshot or Wireframe (optional)
broke

### PR DESCRIPTION
**Pull request by burkeshartsis**
Fixes #409 

## Creator

- [x] Build relevant tests if any apply
- [x] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer

## Reviewer

- [x] Run `test` and make sure all tests pass
- [x] Review function and form on iOS
- [x] Review function and form on Android
- [x] Review function and form on Web
- [x] Review new test logic

### CODE REVIEW

**Comment by burkeshartsis** [comment]
@richarddubay @conrad-vanl can you guys confirm this fixes the address field bug?

**Comment by richarddubay** [comment]
screenshot 2018-03-29 09 53 43

@burkeshartsis From a functionality standpoint, the button is now active. So 🎉 !

**Comment by richarddubay** [comment]
screenshot 2018-03-29 10 24 09

Android looks good.

**Comment by richarddubay** [comment]
screenshot 2018-03-29 10 26 49

As does Web.

**Comment by richarddubay** [comment]
television-justin-bieber-celebs-yC7vLP2q7kUHC

**Pull request merged**
