### PR TITLE
Redirect to home page on web logout to prevent endless redirect bug

### LINKED ISSUE #621: Can't close the login modal after logout
## Acceptance Criteria

- [ ] It should close the login modal when you click the "X".

## Context

Given that a person is on the profile settings page and clicks to sign out when they click the "X" on the resulting login modal then they should be taken back to the homepage.

## UI Screenshot or Wireframe (optional)
So in this screenshot, I had just signed out and the modal pops up to sign back in again:

Then I clicked on the "X" to close the modal and it attempted to go to the profile again, and because I'm not signed in, it brings the modal up again.

### PR DESCRIPTION
**Pull request by conrad-vanl**
Fixes #621 

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [x] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [x] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by IsaacHardy** [comment]
@conrad-vanl Is there anyway to clean up the logout animation/transition to the Home page? The redirect is a great fix, just want to see if there is a way we can make the transition look a little less janky.

**Comment by conrad-vanl** [comment]
Agreed it's currently a bit janky. This was a quick fix. We can leave it open and time permitting on another issues, I'll come back and see if I can clean this up.

**Comment by burkeshartsis** [comment]
Are we going to merge this or add some animation?

**Comment by richarddubay** [comment]
@burkeshartsis If you know how to make this better, please take a shot at it. I'm for merging it and making it better later...but I'm not sure how much later "later" will be. I'm afraid we'd never come back to it. But I think the fix needs to get in because it's currently broken. But that's an @IsaacHardy call.

**Pull request merged**
