### PR TITLE
35-video-component

### LINKED ISSUE #35: Build Video Component
## Acceptance Criteria

- [ ] It should play video
- [ ] It should pause video
- [ ] It should use the Seeker component in `@primitives`
- [ ] Is should show a placeholder image for the video while it's loading
- [ ] The way developers interact with the component should be similar if not the same as the Audio Component

## Context

Given we need to display video when we use the Video component then a video player that works for both web and native appears

### PR DESCRIPTION
**Pull request by Lepozepo**
Fixes #35 

## Creator

- [x] Build relevant tests if any apply
- [x] Ensure there are no new warnings
- [x] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by Lepozepo** [comment]
This isn't 100%, for some reason the calling `setPositionAsync` on `Video` doesn't work as expected. Not sure if there's some sort of trick to it.

**Comment by conrad-vanl** [comment]
@burkeshartsis it's worth reviewing the audio component when looking this over as well, and perhaps any thoughts/discussion that was made in the audio PR: #32

**Comment by mary-pr-poppins** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  No Changelog changes!
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by burkeshartsis** [comment]
Closing this in favor of using a native video player solution. Will readdress issues requirements in #100.

**Pull request closed without merging**
