### PR TITLE
Environment files for local/beta/production 

### PR DESCRIPTION
**Pull request by IsaacHardy**
This PR should streamline the process of creating and populating environment files with Apollos. 

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@IsaacHardy nice. I'm currently working on some related env settings stuff - it looks like env vars aren't getting through on React Native currently (change in how expo expects you to provide env vars). Once I get that to a good place we should sync up and make sure we're attacking all of this the right way.

**Comment by IsaacHardy** [comment]
@conrad-vanl Sounds good! Keep me posted on your progress.

**Comment by IsaacHardy** [comment]
@conrad-vanl Updated script and variable names. Should be ready for review.

**Comment by IsaacHardy** [comment]
Scratch that. Need to update tests.

**Comment by IsaacHardy** [comment]
@conrad-vanl I seem to be having an issue with the `@UI/TestProviders.js`. It cannot seem to read the Settings file that I am importing into the `httpLink.js` for the HeighlinerURL. 

I've done a bit of research and it seems that there could be an issue with the order in which these specific files are being loaded or how they are being translated in babel. 

Do you have any idea as to what could be causing this issue? If you check the Travis console for this build, you will see that every test fails with a `TypeError: Cannot read property 'APP_HEIGHLINER_URL' of undefined`.

**Comment by IsaacHardy** [comment]
@conrad-vanl I am just going to push the absolute url for alpha-heighliner for the time being. We cannot really use the Heighliner env variable effectively until we figure out the how to implement my script with Travis anyways.

**Comment by conrad-vanl** [comment]
Hmmmm. Could be that the jest environment is having difficulty importing `Settings` because it relies on the expo environment to be active. Previously `Settings` was bypassing expo's `Constants` and rolling right into `process.env`, but that's not available in the expo environment. I'll look into this PR some more on monday.

We will probably need to add `APP_HEIGHLINER_URL` to the Travis env vars as well.

**Comment by conrad-vanl** [comment]
@IsaacHardy the issue you explained could be related to the fix with `run-with-settings` I mention in this PR https://github.com/NewSpring/Apollos/pull/305

**Comment by IsaacHardy** [comment]
@conrad-vanl I'll try to pull in the changes for #305 to see if that fixes my issue.

**Comment by IsaacHardy** [comment]
@conrad-vanl Tested locally and your changes (#305) fixed my issue! 

FYI, we obviously haven't setup this script to run with Travis so Netlify doesn't load any data. However, we can use this PR to setup that build process within Travis before we move this to the master branch.

**Pull request merged**
