### PR TITLE
(SYS-4605) Added NEW Short Link Logic

### PR DESCRIPTION
**Pull request by redreceipt**
*MUST* be tested on actual devices

Use this link to test on iOS and Android. Paste into a note or something and then click from there.

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by richarddubay** [comment]
> Use this link to test on iOS and Android. Paste into a note or something and then click from there.

What link?

How do I test this?

**Comment by redreceipt** [comment]
@richarddubay https://newspring.page.link/M5Jz

**Comment by richarddubay** [comment]
@redreceipt So I _tried_ testing this. But I think I failed miserably. I ran the app with the Expo link from `yarn start` and I ran the website from the IP address from `yarn web` ... both on my phone. I clicked the link you showed above from a note on my phone and it still opened up Safari first with the preview page. So either I didn't do something right ... or this didn't work as intended (the intention being that it would not have to open up Safari first and it would go right into the app as it does on Android).

What I'm wondering is if anything needs to happen in the `NewSpring/NewSpring` repo for the website in order to make this work. There is an `app-site-association` file there that handles the universal links for the app ... maybe something needs to happen there for the `newspring.page.link` URL to work as intended? Obviously, I have no clue if this is true ... just something I thought about.

Also obviously, there is a chance that I just tested this incorrectly. If that's true, let me know where I messed it up and I'd be happy to test it again. 👍

**Comment by redreceipt** [comment]
I think you'd be better to load the app via xcode and studio on real
devices instead of trying to use a remote bundle. Since the code is in the
native files.

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by richarddubay** [comment]
This seems to work just fine on iOS. There is currently an issue with Crashlytics on Android. See: https://stackoverflow.com/questions/55194687/no-signature-of-method-com-crashlytics-tools-gradle-crashlyticsplugin. Seems smart to just wait for Fabric to fix this that force us to hardcode the tools version.

**Pull request closed without merging**
