### PR TITLE
Fix topic toggle switches

### LINKED ISSUE #303: Topic Toggle Switches in Profile Section Don't Visually Match Their State
## Acceptance Criteria

- [ ] Topic toggles in the `Profile` section should be a correct visual representation of their current state (enabled/disabled).

## Context

While viewing the `Topics` tab of the `Profile` section, tapping a toggle to disable a topic from the home feed causes the toggle to animate and then snap back to the enabled position. I verified by going to the home feed and pulling to refresh that it does, in fact, filter the content. It appears that the toggles are not visually matching their state.

### PR DESCRIPTION
**Pull request by conrad-vanl**
Fixes #303 

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by conrad-vanl** [comment]
This fixes the optimistic update on the client side, but it appears that topic toggle mutation on heighliner isn't doing anything. I'm going to tag this for @Lepozepo to look at when he's back on monday.

**Comment by Lepozepo** [comment]
This seems to be an issue with `cache: false` on the `currentPerson` query, looking into it

**Comment by Lepozepo** [comment]
Found the issue, pushing a patch to Heighliner in a sec

**Comment by Lepozepo** [comment]
Depends on [heighliner#368](https://github.com/NewSpring/Heighliner/pull/368)

**Comment by conrad-vanl** [comment]
@burkeshartsis assigning this over to you. Can you double check if you go to the topics toggle screen that they behave correctly?

Essentially: you tap them and they toggle correctly. You exit the screen or refresh the app and come back and they still show the correct state (whatever you toggled off is still off)

**Comment by conrad-vanl** [comment]
> come back to profile topics your change is not persisted

@Lepozepo I believe this is what you were looking at on heighliner, correct? I deployed that branch of yours to alpha.

**Comment by conrad-vanl** [comment]
@Lepozepo looks like the build to alpha heighliner isn't working. Stand by on this until I track that down.

**Pull request merged**
