### PR TITLE
Apollo Client

### PR DESCRIPTION
**Pull request by johnthepink**
Set up ApolloClient, integrate with store, etc

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@johnthepink I think we will have to hold off until we have auth on the api and will need to update the endpoint to be from meteor settings

**Comment by johnthepink** [comment]
@jbaxleyiii that's what i'm doing now :)

**Comment by johnthepink** [comment]
@jbaxleyiii this should be ready once we are ready to deploy

**Comment by johnthepink** [comment]
need to rebase ...

**Pull request merged**
