### PR TITLE
Profile Tab

### LINKED ISSUE #177: Profile: dashboard
## Acceptance Criteria

- [ ] It should show profile image at top, tapping on allows you to select an image
- [ ] It should have two tabs: likes and following
- [ ] It should list content for each tab

## TODO:

- [ ] @Lepozepo need to make sure data queries/mutations for this view are supported (or issues are created)

### LINKED ISSUE #178: Profile: settings
## Acceptance Criteria

- [ ] Build out settings menu accessed by clicking on cog icon inside of profile view
- [ ] Items in the settings menu should link out to individual forms (personal details, address, etc)

## TODO

- [ ] @Lepozepo need to make sure data queries/mutations for these views are supported (or issues are created)

### PR DESCRIPTION
**Pull request by conrad-vanl**
Fixes #177 
Fixes #178 

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [x] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@burkeshartsis this introduces a few things stylistically: changes `colors.background.default` to be the gray that they use on NS, and introduces a `colors.background.paper` which is white. Paper is used for elevated items and more prominent element backgrounds. The name "paper" comes form material design spec, if you have idea for better name, lmk. Previously, we were rendering everything with a white background, which was incorrect.

This also implements repsonsive views for profile and settings. They're not perfect yet, but changes will come in with @Lepozepo's giving work (TabBar with white background on desktop) and the integration of profile photo uploading, submitting of settings forms, etc.

Marking this ready for review, but @Lepozepo needs to implement profile photo uploading mutation / heighliner-side and hook up the forms. Do you want to do this in this branch, or open a new issue as follow up?

**Comment by Lepozepo** [comment]
@conrad-vanl I'd rather have a new issue for the pending mutations so we can show some progress on this

**Comment by conrad-vanl** [comment]
Let me get a few things patched up then we can start the review process on this.

**Comment by Lepozepo** [comment]
Issue continues [here](https://github.com/NewSpring/Apollos/issues/260)

**Comment by conrad-vanl** [comment]
Aight, this should be G2G. Who wants to take?

**Comment by burkeshartsis** [comment]
Rotated the device on the my profile details page and got this error
simulator screen shot - iphone x - 2018-01-29 at 17 07 46

**Comment by burkeshartsis** [comment]
Tried to change my birthday on the profile personal details page and got this error
simulator screen shot - iphone x - 2018-01-29 at 17 10 13

**Comment by conrad-vanl** [comment]
@Lepozepo fixed

**Comment by burkeshartsis** [comment]
Account card story displaying incorrectly because of theme color change.
simulator screen shot - iphone x - 2018-01-29 at 17 40 28

**Comment by conrad-vanl** [comment]
> Tried to change my birthday on the profile personal details page and got this error. I can confirm this is the only field that has an issue on this page.
@burkeshartsis fixed. You'll get a warning now, but that'll be fixed when these forms are hooked up i believe.

**Comment by conrad-vanl** [comment]
> Rotated the device on the my personal details page and got this error.
this is fixed in another PR that's opened

**Comment by conrad-vanl** [comment]
> The Audio story throws an error on web and doesn't render on native but that might be unrelated to this PR.

Yeah...un-related. whoops.

**Pull request merged**
