### PR TITLE
59 state tree

### LINKED ISSUE #59: Build new state tree action creators, actions, reducers
## Acceptance Criteria

- [ ] It should closely follow [this](https://github.com/NewSpring/Apollos/issues/45) state tree

## Context

Given a developer needs to tap into business logic when they look at the `@data` directory then they can easily identify how features are coming together

### PR DESCRIPTION
**Pull request by Lepozepo**
Fixes #59 

## Creator

- [x] Build relevant tests if any apply
- [x] Ensure there are no new warnings
- [x] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by mary-pr-poppins** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  No Changelog changes!
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Lepozepo** [comment]
Hey guys! This is in a decent spot right now, it's not integrating with their graphQL yet but it has some actions, reducers, and sagas. I'm being very verbose with the reducers but please let me know if you think we should split them up or if there's anything else that doesn't make any sense to you.

**Comment by Lepozepo** [comment]
Also, you'll notice there are a lot of new files under `@data/.queries`. None of them are being used right now but I went through most of their wrapper components and extracted most of them. This will be very insightful as we build the next parts of the redux tree

**Comment by conrad-vanl** [comment]
Is `@data/.queries` the final spot for these queries, or do we plan on moving them?

**Comment by Lepozepo** [comment]
@conrad-vanl moving them most likely, just wanted to put them somewhere temporary

**Comment by Lepozepo** [comment]
Closing this PR in light of going a non-redux route

**Pull request closed without merging**
