### PR TITLE
Fund Detail Pages Default Fund Update

### PR DESCRIPTION
**Pull request by richarddubay**
This makes it so that the default fund selected in the fund dropdown is the fund of the detail page you're on. So, for example, if you're on the Overflow Offering fund detail page then the fund in the fund dropdown will be for the Overflow Offering by default.

Note: Should be tested thoroughly. Make sure that if you give from the fund page that it actually goes to the correct fund.

### CODE REVIEW

**Comment by redreceipt** [comment]
@richarddubay can you post a couple screenshots of the views this PR addresses?

**Comment by richarddubay** [comment]
Gauntlet Fund Before:
screenshot 2019-02-15 13 48 29

Gauntlet Fund After:
screenshot 2019-02-15 13 48 04

Overflow Offering Before:
screenshot 2019-02-15 13 48 39

Overflow Offering After:
screenshot 2019-02-15 13 48 14

@redreceipt These are the visual differences. This is awesome because now the link on the Gauntlet page that Brandon showed us can go to the fund page with the fund already selected. So all the giver has to do is put in the amount and go.

**Comment by redreceipt** [comment]
On web it worked great, on iOS, the link did not take me to the app. It stayed in Safari.

kapture 2019-02-15 at 14 59 59

**Comment by richarddubay** [comment]
@redreceipt Well, I'm not sure about the link on that page and if it is supposed to open up the app or if it is supposed to stay in Safari. It looks like links to my.newspring.cc from other places just stay in Safari. If I go to newspring.cc and through the menu pick Give > Give Now, it goes to my.newspring.cc in Safari and doesn't open the app. I don't think that has any bearing on this PR though. This PR just changes the default fund in the dropdown. We should probably make an issue in Jira for what you're seeing. 

For the iOS Sim, I just went into the app, went to Give, and then picked the Overflow Offering or Gauntlet Fund and made sure that the drop down was defaulted correctly. You can see that in the image. 

screenshot 2019-02-15 16 31 53

If you want to test it from a web perspective in the iOS Sim, you can do that but it's a little wonky. You have to change the APP_ROOT_URL in the Apollos `.env` file to be `http://localhost:3000`, start up the app (`yarn start`), start up the web (`yarn web`) and then run the app in the sim. Once that's loaded, go to Safari on the sim, put in something like `newspring.cc`, go to give and it will take you to `my.newspring.cc`. Change the beginning part to `http://localhost:3000` and it will show you what it will look like when these changes are live in production. Does that make sense?

**Pull request merged**
