### PR TITLE
[SYS-4551] Creates an alternate giving flow requiring login.

### PR DESCRIPTION
**Pull request by cdanwards**
Fixes [SYS-4551](https://newspring.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=SYS&modal=detail&selectedIssue=SYS-4551)

Problem this fixes:
Currently, on the give now page, if you enter an amount to give before you sign in then that amount does not persist through login and you have to re-enter that amount. This will require sign in before an amount can be entered into the input, thuse working around the problem.

Decisions Made:
This is a new design for the flow of the give now screen. It doesn't functionally change much, because we made the decision in the initial development that we would not allow guest gifts, thus a login is required.

Creator
-------

- [x] Build relevant tests if any apply
- [x] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer

Reviewer
--------

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by IsaacHardy** [comment]
@cdanwards Conflicts in code need resolving.

**Comment by cdanwards** [comment]
@IsaacHardy I fixed those merge conflicts. Should we decide to go with this flow, I believe it would negate the necessity of some of the other open PRs.

**Comment by richarddubay** [comment]
@cdanwards Is this still needed? Does the problem still exist? There are some conflicts now that we've replaced branches that will need to be fixed if so.

**Comment by IsaacHardy** [comment]
@cdanwards To add on to @richarddubay questions from the comment above, how do we stand on this PR? What do we need to do to move it forward?

**Pull request closed without merging**
