### PR TITLE
342 Web: Giving Account Styles

### LINKED ISSUE #342: WEB: Giving Account Styles
## Acceptance Criteria

- [ ] The styling for the web version of giving accounts show be less redundant and larger in width to display all of the desired content. 

## Context

Currently when creating or viewing an existing account on the giving page in web, there seems to be two vertical black closing buttons to send you back to the giving page. This works well on Native, but looks odd on web. Also, the width of this container could be larger for the content within. 

## UI Screenshot or Wireframe (optional)
screen shot 2018-02-14 at 10 31 53 am

screen shot 2018-02-14 at 10 40 43 am

### PR DESCRIPTION
**Pull request by cdanwards**
Fixes #342 

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

Removed `asModal` from being used in `AppRouter` on these routes.

### CODE REVIEW

**Comment by IsaacHardy** [comment]
Cannot review this PR until the expo build passes. Have you looked into why it might be failing?

**Comment by cdanwards** [comment]
@IsaacHardy In the details it's stating 
>This project does not exist
>Experience with name '@newspring-builds/newspring-326-giving-account-styles' does not exist.

I'm unsure how exactly this works.

**Comment by burkeshartsis** [comment]
Expo builds sometimes just fail. It's dumb @conrad-vanl has had it on the low priority todo list for a while to look into it. We should be able to verify this works locally via `yarn start` (native) and `yarn web`. The only test that is required to pass is CI. Assuming it works locally and tests are passing everywhere it should be able to be reviewed and merged.

**Comment by IsaacHardy** [comment]
@burkeshartsis @cdanwards I've tested on both web and mobile and the issue is resolved.

**Comment by conrad-vanl** [comment]
FWIW, hitting "restart job" on travis usually fixes it

**Comment by conrad-vanl** [comment]
Travis does the expo build

**Pull request merged**
