### PR TITLE
Sermon audio

### LINKED ISSUE #328: Sermon audio
Sermons need "Listen to Audio" button

### PR DESCRIPTION
**Pull request by conrad-vanl**
Fixes #328

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [x] Run `test` and make sure all tests pass
- [x] Review function and form on iOS
- [x] Review function and form on Android
- [x] Review function and form on Web
- [x] Review new test logic

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@burkeshartsis I got the first part of this done - setting up the mediaPlayer store to play arbitrary tracks. Now we just need the UI in sermons that fires the action. Here's how you'd do it:

Use the `withNowPlaying` HOC:

```
import { withMediaPlayerActions } from '@data/mediaPlayer'
```

Which adds a function in to the component's prop `setNowPlaying`, which looks like this:

```
this.props.setNowPlaying({
  currentTrack: {
    title: PropTypes.string,
    file: PropTypes.string,
    duration: PropTypes.string,
  },
  playlist: {
    title: PropTypes.string.isRequired,
    images: ConnectedImage.propTypes.source.isRequired,
    colors: PropTypes.arrayOf(PropTypes.shape({ value: PropTypes.string })).isRequired,
    tracks: PropTypes.arrayOf(track), // optional: omit if there's only the current track
  },
});
```

**Comment by IsaacHardy** [comment]
How is the progress coming on this PR?

**Comment by burkeshartsis** [comment]
@IsaacHardy it's mostly done. Need to sort out some bugs that @conrad-vanl probably wasn't able to test till we had a UI for it. Hoping to get it reviewed by EOD.

**Comment by burkeshartsis** [comment]
So technically this works now. However, the media player (bottom of the screen) was designed for multiple track albums as that was it's original use case. Sermon audio (and something we maybe haven't thought completely thought but a worship single) is only a single track. To really complete this PR we need to update the media player to no show player controls that aren't relevant to a playlist with only 1 track (i.e. next, previous, shuffle).

**Comment by conrad-vanl** [comment]
You might look and see what the current app does. IRC, it still shows those player controls

**Comment by burkeshartsis** [comment]
Another issue I'm seeing is that the apps seems to get super unresponsive once sermon audio has been triggered. Wondering if there is some runaway code somewhere.

**Comment by conrad-vanl** [comment]
> Another issue I'm seeing is that the apps seems to get super unresponsive once sermon audio has been triggered. Wondering if there is some runaway code somewhere.

Try in production mode. I've noticed this issue in dev a few times, but haven't been able to reproduce consistently and in production.

**Comment by burkeshartsis** [comment]
This isn't a problem currently because we redirect web traffic but if we didn't web would be broken as the `id` string [here](https://github.com/NewSpring/Apollos/blob/sermon-audio/src/music/Player/index.js#L174) is undefined for sermon audio. @conrad-vanl thoughts.

**Comment by burkeshartsis** [comment]
This error appears when you select the more (...) overflow in the fullscreen audio player 😢

**Pull request merged**
