### PR TITLE
Eject 🔥👩‍🚒

### PR DESCRIPTION
**Pull request by conrad-vanl**
💀

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [x] Run `test` and make sure all tests pass
- [x] Review function and form on iOS
- [x] Review function and form on Android
- [x] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by conrad-vanl** [comment]
Good luck, feel like we should draw straws to figure out who should review this.

**Comment by IsaacHardy** [comment]
Only 12k+ file changes? pfft

**Comment by conrad-vanl** [comment]
Documenting this now: 

To "unject", we need to revert the file changes to `package.json`, remove the `isDetached` and `detach` keys from `app-config.js`, and delete the `ios` and `android` folders.

**Comment by conrad-vanl** [comment]
To run the app now, you have to run `yarn start` and then open android studio or xcode and press run. I feel like this experience is going to be very blah.

**Comment by conrad-vanl** [comment]
I said that we'd still have compatibility with the expo client and could run the app in the expo client...and while we _can_ do that, I have to make some changes to the setup to support both. So...yeah. Not sure what to do yet.

**Comment by conrad-vanl** [comment]
I. Really. Don't. Want. To. Do. This.

But....Universal links work!

**Comment by IsaacHardy** [comment]
@conrad-vanl @burkeshartsis I was successful in running the app on Android Studio and Xcode. Hot reloading work correctly as well.

What do I need to test specifically to pass these PR?

**Comment by conrad-vanl** [comment]
@IsaacHardy can you expand on the errors you're running into? I tried running `yarn run web` locally and checked out the deploy preview for this branch - https://deploy-preview-498--apollos.netlify.com/

Both seem to be working okay

**Comment by conrad-vanl** [comment]
> What do I need to test specifically to pass this PR?

@IsaacHardy it would probably be good to understand the deployment process, make sure you're comfortable with that. I'm not sure if we can still use `exp build` or not, I havent tried it.

**Comment by IsaacHardy** [comment]
@conrad-vanl Here is the error I receive on web. Although I have looked into solving it yet.
screen shot 2018-04-12 at 1 05 57 pm

**Comment by IsaacHardy** [comment]
@conrad-vanl "`exp build` is not supported for detached projects" - Just received this error message.

**Pull request merged**
