### PR TITLE
Fix HTML headers, improve HTML rendering consistency

### PR DESCRIPTION
**Pull request by conrad-vanl**
Fixes issue where headers weren't showing up in content views.

As evident by the snapshot changes, this also results in dramatically shorter render trees.

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [x] Run `test` and make sure all tests pass
- [x] Review function and form on iOS
- [x] Review function and form on Android
- [x] Review function and form on Web
- [x] Review new test logic

### CODE REVIEW

**Comment by burkeshartsis** [comment]
Current issues:
- [ ] iOS: clips title text
- [ ] Android: Psalm rendering collapses on itself (see below).
- [ ]  Android: Scripture missing line height and titles overlapping verses (see below).

**Comment by burkeshartsis** [comment]
### Android: Psalm rendering collapses on itself (see below)
screenshot_1517935659

**Comment by burkeshartsis** [comment]
### Android: Scripture missing line height and titles overlapping verses
screenshot_1517936676

**Comment by richarddubay** [comment]
Red letters! Nice.

**Pull request merged**
