### PR TITLE
card stack transitions

### LINKED ISSUE #56: create card stack transitions
## Acceptance Criteria

- [ ] Card stack has native-esque style page transitions
- [ ] Can swipe to go back (iOS only)

### PR DESCRIPTION
**Pull request by conrad-vanl**
Fixes #56 

~This PR is currently pointing at #96, which is why I think the commit log is a little dirty (showing the 90-upgrade-apollo changes, for example). After #96 is merged lets edit this pr to point at master.~

Adds in horizontal transitions and swipe to go back functionality.

The majority of this PR is in `@modules/CardStack/Transitioner.js`. The difficulty in trying to achieve card-stack style transitions with react-router is that it mirrors browser history, as in there's a single `history` object with an array of `locations` that have been visited. Even when you have nested `routes`, everything boils up to a single `history` object. Something like `react-navigation` and more traditional `react-native` navigation solutions have this concept of "Navigators" that contain the routing history just for a single level of routes - nested Navigators in this paradigm each manage their own state.

With ReactRouter, we have to keep in mind of routing state and history at a global level. So `Transitioner` needs to consider this when deciding how to transition routes - tapping on Tabs in the TabBar, for example, shouldn't cause a CardStack animation to trigger.

In this PR, `<CardStack>` will only animate routing changes that deal with CardStack's direct child `<Route>`.

For example:

```
<CardStack>
  <Route tabs>
     <Route one />
     <Route two />
  </Route>
  <Route page />
</CardStack>
```

If you navigate from tabs one to tabs two, `CardStack` will not trigger in animation. But if you navigate from `tabs` to `page`, you will get an animation.

## Creator

- [ ] Build relevant tests if any apply
- [x] Ensure there are no new warnings
- [x] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by mary-pr-poppins** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please assign someone to merge this PR, and optionally include people who should review.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  No Changelog changes!
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by conrad-vanl** [comment]
@burkeshartsis got this all synced up with master and ready to review

**Comment by conrad-vanl** [comment]
I originally had this assigned to @burkeshartsis, of which I'd still like you to look at it. But was thinking about this a little and @Lepozepo you might look at it as well / instead...I think you're more familiar with React Router then either of us, and this isn't so much visually concerned as it is structuring how we're going to do routing. Would love your thoughts on this.

This PR is paired along with #111

**Comment by conrad-vanl** [comment]
@Lepozepo here's the only warning i'm seeing, and frankly, I'm not quite sure how to fix:

image

In the audio player, I think it's this:

image

**Comment by Lepozepo** [comment]
Yeah, I noticed that too but figured that component is probably going to disappear anyway. I was talking about `web` not `native` though. There's like 4 or 5 new warnings there. Do you see them?

**Comment by conrad-vanl** [comment]
@Lepozepo got it. I fixed most of the warnings. There's one that I'm still unsure why it's triggering:

image

The propTypes:

image

It's being rendered here:

image


I don't see how `pop` is being set to a string containing "false". Do you?

**Pull request merged**
