### PR TITLE
Back Button hitSlop

### LINKED ISSUE #350: Look at touchable area on back button
> Finally, I don't see this as an issue yet, but the back button on pages where you go into a devo or article or something is really hard to press.  It typically takes multiple presses to find the right space to get it to go back.  Not sure if it's just a sizing issue with the clickable space, or if it's something more complicated.

### PR DESCRIPTION
**Pull request by burkeshartsis**
Fixes #350 

## Creator

- [x] Build relevant tests if any apply
- [x] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by IsaacHardy** [comment]
@conrad-vanl @burkeshartsis When should I expect this PR to be ready for merge?

**Comment by conrad-vanl** [comment]
@IsaacHardy there's currently an issue on this PR with iOS devices. So @burkeshartsis is working through taht now.

**Comment by IsaacHardy** [comment]
@conrad-vanl Sounds good. I still need to make one final build before we leave to ATL.

**Comment by burkeshartsis** [comment]
Alright, I think that last commit (eda8f34) did the trick.

**Comment by conrad-vanl** [comment]
Ehhh....i'm still experiencing issues

**Comment by burkeshartsis** [comment]
😢

**Comment by burkeshartsis** [comment]
so the question we all have the answer to now is, "how many engineers and devices does it take to make a tappable button?" 😬

**Pull request merged**
